from flask import Flask
from flask import request
from flask import jsonify
from telebot import types
from telepot.namedtuple import (ReplyKeyboardMarkup, KeyboardButton, ReplyKeyboardRemove)
from telegram.ext import (Updater, CommandHandler, CallbackQueryHandler, ConversationHandler, Filters)
import polling
import telepot
import simplejson as json
import requests
import telebot
import logging
from json import dumps, loads, JSONEncoder, JSONDecoder

app = Flask(__name__)
bot = telebot.TeleBot('560420481:AAGSBQpupKG7fzhUkr905FuW6u-ORFvVK80')

URL = 'https://api.telegram.org/bot560420481:AAGSBQpupKG7fzhUkr905FuW6u-ORFvVK80/'

@bot.message_handler(commands=['help', 'start'])
def send_welcome(message):
    keyboard = types.ReplyKeyboardMarkup(row_width=1, resize_keyboard=True, one_time_keyboard=True)
    button_phone = types.KeyboardButton(text="Отправить мой номер", request_contact=True)
    keyboard.add(button_phone)
    bot.send_message(message.chat.id,'Привет!\n Я - @cocopalmsalon_bot, личный помощник салона красоты "Коко Пальм"\n Рад тебя приветствовать! \n Для авторизации нажми, пожалуйста, кнопку "Отправить мой номер"', reply_markup=keyboard)


def handle_messages(messages):
    for message in messages:
        if message.contact is not None:
            bot.send_message(message.chat.id, 'Напиши свою дату рождения. Обещаю, я никому не скажу. Это будет нашим маленьким секретом (укажите свою дату рождения в формате ДД.ММ)')

bot.set_update_listener(handle_messages)
current_message = last_message = None

@bot.message_handler(content_types=["text"])
def keyboard_menu(message):
    print("keyboard menu")
    if len(message.text) == 5 and message.text[0].isdigit() and message.text[1].isdigit() and message.text[2]=="." and message.text[3].isdigit() and message.text[4].isdigit():
        markup = types.ReplyKeyboardMarkup()
        markup.row("F.A.Q.", "Заказать процедуру")
        markup.row("Отзывы о работе мастеров", "Портфолио")
        markup.row("Хочу быть моделью")
        bot.send_message(message.chat.id, "Спасибо за регистрацию, добро пожаловать в главное меню!", reply_markup=markup)

    print("model")
    if message.text == "Хочу быть моделью":
        key = types.InlineKeyboardMarkup()
        button_1 = types.InlineKeyboardButton(text = "Окрашивание", callback_data="Окрашивание")
        button_2 = types.InlineKeyboardButton(text = "Прическа", callback_data="Прическа")
        button_3 = types.InlineKeyboardButton(text = "Макияж", callback_data="Макияж")
        key.add(button_1)
        key.add(button_2)
        key.add(button_3)
        bot.send_message(message.chat.id, "Моделью какой категории хотите быть?", reply_markup=key)

    print("zakaz")
    if message.text == "Заказать процедуру":
        key = types.InlineKeyboardMarkup()
        button_1 = types.InlineKeyboardButton(text = "Мужские стрижки", callback_data="Мужские стрижки")
        button_2 = types.InlineKeyboardButton(text = "Женские стрижки", callback_data="Женские стрижки")
        button_3 = types.InlineKeyboardButton(text = "Маникюр", callback_data="Маникюр")
        button_4 = types.InlineKeyboardButton(text = "Педикюр", callback_data="Педикюр")
        button_5 = types.InlineKeyboardButton(text = "Косметология", callback_data="Косметология")
        button_6 = types.InlineKeyboardButton(text = "SHR-эпиляция женский зал", callback_data="SHR-эпиляция женский зал")
        button_7 = types.InlineKeyboardButton(text = "SHR-эпиляция мужской зал", callback_data="SHR-эпиляция мужской зал")
        button_8 = types.InlineKeyboardButton(text = "Солярий", callback_data="Солярий")
        button_9 = types.InlineKeyboardButton(text = "Шугаринг женский зал", callback_data="Шугаринг женский зал")
        button_10 = types.InlineKeyboardButton(text = "Шугаринг мужской зал", callback_data="Шугаринг мужской зал")
        button_11 = types.InlineKeyboardButton(text = "БРОВИ И РЕСНИЦЫ", callback_data="БРОВИ И РЕСНИЦЫ")
        button_12 = types.InlineKeyboardButton(text = "Татуаж", callback_data="Татуаж")
        button_13 = types.InlineKeyboardButton(text = "Отбеливание зубов Smile ROOM", callback_data="Отбеливание зубов Smile ROOM")
        button_14 = types.InlineKeyboardButton(text = "Макияж", callback_data="Макияж")
        key.add(button_1)
        key.add(button_2)
        key.add(button_3)
        key.add(button_4)
        key.add(button_5)
        key.add(button_6)
        key.add(button_7)
        key.add(button_8)
        key.add(button_9)
        key.add(button_10)
        key.add(button_11)
        key.add(button_12)
        key.add(button_13)
        key.add(button_14)
        bot.send_message(message.chat.id, "Выберите категорию процедуры", reply_markup=key)

    print("faq")
    if message.text == "F.A.Q.":
        bot.send_message(message.chat.id, "Введите ваш вопрос, я постараюсь на него ответить.")
        if message.text == "Сколько стоит окрашивание волос?" or "Сколько стоит мелирование волос?" \
        or "Сколько стоит колорирование волос?" or "Сколько стоит шатуш волос?" \
        or "Сколько стоит балаяж волос?" or "Сколько стоит омбре волос?":
            bot.send_message(message.chat.id, text = "Все очень индивидуально. Для того чтобы как можно точнее просчитать стоимость ответьте пожалуйста на несколько вопросов")
            bot.send_message(message.chat.id, "Длина ваших волос?")
            if message.text == answer:
                bot.send_message(message.chat.id, "Исходный цвет ваших волос?")
                if message.text == answer:
                    bot.send_message(message.chat.id, "Окрашены ли Ваши волосы красителем или хной?(ответ да или нет)")
                    if message.text == "да":
                        bot.send_message(message.chat.id, "Окрашивание производилось в домашних условиях или в рамках салона профессиональнымкрасителем?")
                        if message.text  == answer:
                            bot.send_message(message.chat.id, "Окрашивание какого характера планируется? (в один тон, с осветлением, переходом,мелирование)")
                    else: 
                        bot.send_message(message.chat.id, "Окрашивание какого характера планируется? (в один тон, с осветлением, переходом,мелирование)")
                        if message.text == answer:
                            bot.send_message(message.chat.id, "Спасибо за ваши ответы, с вам свяжется наш администратор.")
        else:
            bot.send_message(message.chat.id, "Мы ничего не нашли по вашему вопросу, можете спросить у нашего администратора @DaryaPetkevich")

        if message.text == "Сколько стоит ламинирование волос?"or "Сколько стот кератиновое выпрямление волос?"\
        or "Сколько стоит ботокс?" or "Сколько стоит гиалуроновое востановление?" or "Сколько стоит профайбер?":
            bot.send_message(message.chat.id, "Все очень индивидуально. Для того чтобы как можно точнее просчитать стоимость ответьте пожалуйста на несколько вопросов", reply_markup=key)
            bot.send_message(message.chat.id, "Длина ваших волос?", reply_markup=markup)
            if message.text is not None :
                bot.send_message(message.chat.id, "Примерная густота Ваших волос (очень густые, средней густоты, не очень густые)?", reply_markup=markup)
                if message.text is not None :
                    bot.send_message(message.chat.id, "Спасибо за ваши ответы, с вам свяжется наш администратор.", reply_markup=markup)
        else:
            bot.send_message(message.chat.id, "Мы ничего не нашли по вашему вопросу, можете спросить у нашего администратора @DaryaPetkevich", reply_markup=markup)

        if message.text == "Сколько стоит укладка?":
            bot.send_message(message.chat.id, "Все очень индивидуально. Для того чтобы как можно точнее просчитать стоимость ответьте пожалуйста на несколько вопросов", reply_markup=key)
            bot.send_message(message.chat.id, "Длина ваших волос?", reply_markup=markup)
            if message.text is not None:
                bot.send_message(message.chat.id, "Какой вид укладки планируете делать(локоны, выпрямление на утюжок, укладка фен)?", reply_markup=markup)
                if message.text is not None:
                    bot.send_message(message.chat.id, "Какой стайлинг планируете использовать(сильной фиксации, средней фиксации, без стайлинга)?", reply_markup=markup)
                    if message.text is not None:
                        bot.send_message(message.chat.id, "Спасибо за ваши ответы, с вам свяжется наш администратор.", reply_markup=markup)
        else:
            bot.send_message(message.chat.id, "Мы ничего не нашли по вашему вопросу, можете спросить у нашего администратора @DaryaPetkevich", reply_markup=markup)

        if message.text == "Сколько стоит причёска?":
            bot.send_message(message.chat.id, "Все очень индивидуально. Для того чтобы как можно точнее просчитать стоимость ответьте пожалуйста на несколько вопросов", reply_markup=key)
            bot.send_message(message.chat.id, "Длина ваших волос?", reply_markup=markup)
            if message.text is not None:
                bot.send_message(message.chat.id, "Какого характера планируется прическа (локоны, коса, пучок, другое)?", reply_markup=markup)
                if message.text is not None:
                    bot.send_message(message.chat.id, "Спасибо за ваши ответы, с вам свяжется наш администратор.", reply_markup=markup)
        else:
            bot.send_message(message.chat.id, "Мы ничего не нашли по вашему вопросу, можете спросить у нашего администратора @DaryaPetkevich", reply_markup=markup)

        if message.text == "Сколько стоит женская стрижка?":
            key = types.InlineKeyboardMarkup()
            button_1 = types.InlineKeyboardButton(text = "Короткая 750 руб.", callback_data="Короткая")
            button_2 = types.InlineKeyboardButton(text = "Средняя длинна 1050 руб.", callback_data="Средняя длинна")
            button_3 = types.InlineKeyboardButton(text = "Комплекс женский 1350 руб.", callback_data="Комплекс женский")
            button_4 = types.InlineKeyboardButton(text = "Мытье головы 150 руб.", callback_data="Мытье головы")
            button_5 = types.InlineKeyboardButton(text = "Уходовая маска 150 руб.", callback_data="Уходовая маска")
            button_6 = types.InlineKeyboardButton(text = "Стрижка кончиков 400 руб.", callback_data="Стрижка кончиков")
            button_7 = types.InlineKeyboardButton(text = "Оформление чёлки 250 руб.", callback_data="Оформление чёлки")
            button_8 = types.InlineKeyboardButton(text = "Укладка феном 500-700 руб.", callback_data="Укладка феном")
            button_9 = types.InlineKeyboardButton(text = "Плетение кос от 500 руб.", callback_data="Плетение кос")
            button_10 = types.InlineKeyboardButton(text = "Вечерняя причёска 2000-2500 руб.", callback_data="Вечерняя причёска")
            button_11 = types.InlineKeyboardButton(text = "Кератиновое выпрям. от 2500 руб.", callback_data="Кератиновое выпрям.")
            button_12= types.InlineKeyboardButton(text = "Окрашивание волос от 3000 руб.", callback_data="Окрашивание волос")
            button_13 = types.InlineKeyboardButton(text = "Снятие цвета от 1500 руб.", callback_data="Снятие цвета")
            key.add(button_1)
            key.add(button_2)
            key.add(button_3)
            key.add(button_4)
            key.add(button_5)
            key.add(button_6)
            key.add(button_7)
            key.add(button_8)
            key.add(button_9)
            key.add(button_10)
            key.add(button_11)
            key.add(button_12)
            key.add(button_13)
            bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, reply_markup=key)
        else:
            bot.send_message(message.chat.id, "Мы ничего не нашли по вашему вопросу, можете спросить у нашего администратора @DaryaPetkevich", reply_markup=markup)

        if message.text == "Сколько стоит эпиляция?":
            bot.send_message(message.chat.id, "Какой зал вас интересует?(мужской, женский)", reply_markup=markup)
            if message.text == "женский":
                bot.send_message(message.chat.id, "Выберите процедуру которую хотите заказать", reply_markup=key)
                key = types.InlineKeyboardMarkup()
                button_1 = types.InlineKeyboardButton(text = "Классическое бикини 3100 руб.", callback_data="Классическое бикини")
                button_2 = types.InlineKeyboardButton(text = "Глубокое бикини 5000 руб.", callback_data="Глубокое бикини")
                button_3 = types.InlineKeyboardButton(text = "Живот 1500-3200 руб.", callback_data="Живот")
                button_4 = types.InlineKeyboardButton(text = "Ноги (бедра) 8300 руб.", callback_data="Ноги (бедра)")
                button_5 = types.InlineKeyboardButton(text = "Ноги (голень) 4700 руб.", callback_data="Ноги (голень)")
                button_6 = types.InlineKeyboardButton(text = "Ноги полностью 9800 руб.", callback_data="Ноги полностью")
                button_7 = types.InlineKeyboardButton(text = "Пальцы ног 900 руб.", callback_data="Пальцы ног")
                button_8 = types.InlineKeyboardButton(text = "Подмышечные впадины 2300 руб.", callback_data="Подмышечные впадины")
                button_9 = types.InlineKeyboardButton(text = "Руки до локтя 3700 руб.", callback_data="Руки до локтя")
                button_10 = types.InlineKeyboardButton(text = "Руки полностью 5100 руб.", callback_data="Руки полностью")
                button_11 = types.InlineKeyboardButton(text = "Верхняя губа 950 руб.", callback_data="Верхняя губа")
                button_12 = types.InlineKeyboardButton(text = "Шея 1200-2800 руб.", callback_data="Шея")
                button_13 = types.InlineKeyboardButton(text = "Щеки 1800 руб.", callback_data="Щеки")
                button_14 = types.InlineKeyboardButton(text = "Подбородок 850 руб.", callback_data="Подбородок")
                button_15 = types.InlineKeyboardButton(text = "Бакенбарды 1200 руб.", callback_data="Бакенбарды")
                key.add(button_1)
                key.add(button_2)
                key.add(button_3)
                key.add(button_4)
                key.add(button_5)
                key.add(button_6)
                key.add(button_7)
                key.add(button_8)
                key.add(button_9)
                key.add(button_10)
                key.add(button_11)
                key.add(button_12)
                key.add(button_13)
                key.add(button_14)
                key.add(button_15)
                bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, reply_markup=key)
            elif message.text == "мужской":
                bot.send_message(message.chat.id, "Выберите процедуру которую хотите заказать", reply_markup=key)
                key = types.InlineKeyboardMarkup()
                button_1 = types.InlineKeyboardButton(text = "Бакенбарды 1200 руб.", callback_data="Бакенбарды")
                button_2 = types.InlineKeyboardButton(text = "Щеки 2300 руб.", callback_data="Щеки")
                button_3 = types.InlineKeyboardButton(text = "Грудь 4700 руб.", callback_data="Грудь")
                button_4 = types.InlineKeyboardButton(text = "Живот полностью 5000-6600 руб.", callback_data="Живот полностью")
                button_5 = types.InlineKeyboardButton(text = "Живот нижняя часть 4800 руб.", callback_data="Живот нижняя часть")
                button_6 = types.InlineKeyboardButton(text = "Ноги до колена 6600 руб.", callback_data="Ноги до колена")
                button_7 = types.InlineKeyboardButton(text = "Ноги полностью 11200 руб.", callback_data="Ноги полностью")
                button_8 = types.InlineKeyboardButton(text = "Пальцы ног 1800 руб.", callback_data="Пальцы ног")
                button_9 = types.InlineKeyboardButton(text = "Подмышечные впадины 2700 руб.", callback_data="Подмышечные впадины")
                button_10 = types.InlineKeyboardButton(text = "Руки до локтя 5000 руб.", callback_data="Руки до локтя")
                button_11 = types.InlineKeyboardButton(text = "Рики полностью 7100 руб.", callback_data="Рики полностью")
                button_12 = types.InlineKeyboardButton(text = "Спина 9500 руб.", callback_data="Спина")
                button_13 = types.InlineKeyboardButton(text = "Шея (задняя часть) 2300 руб.", callback_data="Шея (задняя часть)")
                button_14 = types.InlineKeyboardButton(text = "Шея (передняя часть) 2300 руб.", callback_data="Шея (передняя часть)")
                button_15 = types.InlineKeyboardButton(text = "Лицо полностью 4800 руб.", callback_data="Лицо полностью")
                key.add(button_1)
                key.add(button_2)
                key.add(button_3)
                key.add(button_4)
                key.add(button_5)
                key.add(button_6)
                key.add(button_7)
                key.add(button_8)
                key.add(button_9)
                key.add(button_10)
                key.add(button_11)
                key.add(button_12)
                key.add(button_13)
                key.add(button_14)
                key.add(button_15)
                bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, reply_markup=key)
        else:
            bot.send_message(message.chat.id, "Мы ничего не нашли по вашему вопросу, можете спросить у нашего администратора @DaryaPetkevich", reply_markup=markup)

        if message.text == "Сколько стоит шугаринг?":
            bot.send_message(message.chat.id, "Стоимость зависит от зоны обработки. Напишите какой зал вас интересует.(мужской, женский)", reply_markup=markup)
            if message.text == "женский":
                key = types.InlineKeyboardMarkup()
                button_1 = types.InlineKeyboardButton(text = "Класический бикини 950 руб.", callback_data="Класический бикини")
                button_2 = types.InlineKeyboardButton(text = "Глубокое бикини 1500 руб.", callback_data="Глубокое бикини")
                button_3 = types.InlineKeyboardButton(text = "Голень 750 руб.", callback_data="Голень")
                button_4 = types.InlineKeyboardButton(text = "Ноги полностью 1200 руб.", callback_data="Ноги полностью")
                button_5 = types.InlineKeyboardButton(text = "Руки полностью 650 руб.", callback_data="Руки полностью")
                button_6 = types.InlineKeyboardButton(text = "Лицо 300 руб.", callback_data="Лицо")
                button_7 = types.InlineKeyboardButton(text = "Подмышки 450 руб.", callback_data="Подмышки")
                key.add(button_1)
                key.add(button_2)
                key.add(button_3)
                key.add(button_4)
                key.add(button_5)
                key.add(button_6)
                key.add(button_7)
                bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, reply_markup=key)
            elif message.text == "мужской":
                key = types.InlineKeyboardMarkup()
                button_1 = types.InlineKeyboardButton(text = "Грудь 1500 руб.", callback_data="Грудь")
                button_2 = types.InlineKeyboardButton(text = "Спина 1500 руб.", callback_data="Спина")
                button_3 = types.InlineKeyboardButton(text = "Живот 1000 руб.", callback_data="Живот")
                button_4 = types.InlineKeyboardButton(text = "Ноги полностью 2500 руб.", callback_data="Ноги полностью")
                button_5 = types.InlineKeyboardButton(text = "Ноги голень 1400 руб.", callback_data="Ноги голень")
                button_6 = types.InlineKeyboardButton(text = "Ягодицы 750 руб.", callback_data="Ягодицы")
                button_7 = types.InlineKeyboardButton(text = "Руки полностью 1150 руб.", callback_data="Руки полностью")
                button_8 = types.InlineKeyboardButton(text = "Руки до локтя 750 руб.", callback_data="Руки до локтя")
                button_9 = types.InlineKeyboardButton(text = "Лицо 500 руб.", callback_data="Лицо")
                button_10 = types.InlineKeyboardButton(text = "Подмышки 650 руб.", callback_data="Подмышки")
                button_11 = types.InlineKeyboardButton(text = "Класическое бикини 2500 руб.", callback_data="Класическое бикини")
                button_12 = types.InlineKeyboardButton(text = "Глубокое бикини 4000 руб.", callback_data="Глубокое бикини")
                key.add(button_1)
                key.add(button_2)
                key.add(button_3)
                key.add(button_4)
                key.add(button_5)
                key.add(button_6)
                key.add(button_7)
                key.add(button_8)
                key.add(button_9)
                key.add(button_10)
                key.add(button_11)
                key.add(button_12)
                bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, reply_markup=key)
        else:
            bot.send_message(message.chat.id, "Мы ничего не нашли по вашему вопросу, можете спросить у нашего администратора @DaryaPetkevich", reply_markup=markup)

        if message.text == "Сколько стоит татуировка?":
            bot.send_message(message.chat.id, "Все очень индивидуально. Для того чтобы как можно точнее просчитать стоимость ответьте пожалуйста на несколько вопросов", reply_markup=key)
            bot.send_message(message.chat.id, "Наком участке тела планируется татуировка?", reply_markup=markup)
            if message.text is not None:
                bot.send_message(message.chat.id, "Ориентировочный размер(ладонь, пол ладони, две латони, больше двух ладоней?", reply_markup=markup)
                if message.text is not None:
                    bot.send_message(message.chat.id, "Спасибо за ваши ответы, с вам свяжется наш администратор.", reply_markup=markup)
        else:
            bot.send_message(message.chat.id, "Мы ничего не нашли по вашему вопросу, можете спросить у нашего администратора @DaryaPetkevich", reply_markup=markup)

        if message.text == "Сколько стоит нарашивание ресниц?":
            bot.send_message(message.chat.id, "Какой объем планируете наращивать (класика, 2д, 3д)?", reply_markup=markup)
            if message.text is not None:

                button_1 = types.InlineKeyboardButton(text = "Наращивание ресниц 1800 руб.", callback_data="Наращивание ресниц")
                button_2 = types.InlineKeyboardButton(text = "Наращивание ресниц 2д 2000 руб.", callback_data="Наращивание ресниц 2д")
                button_3 = types.InlineKeyboardButton(text = "Наращивание ресниц 3д 2300 руб.", callback_data="Наращивание ресниц 3д")
                key.add(button_1)
                key.add(button_2)
                key.add(button_3)
        else:
            bot.send_message(message.chat.id, "Мы ничего не нашли по вашему вопросу, можете спросить у нашего администратора @DaryaPetkevich", reply_markup=markup)

        if message.text == "Сколько стоит маникюр?" or "Сколько стоит педикюр?" or "Сколько стоят брови?":
            bot.send_message(message.chat.id, "Обратитесь к главному меню и нажмите кнопку 'Заказать процедуру'. Там вы сможете найти пhайслист наших услуг.", reply_markup)
        else:
            bot.send_message(message.chat.id, "Мы ничего не нашли по вашему вопросу, можете спросить у нашего администратора @DaryaPetkevich", reply_markup=markup)

        if message.text == "Можно записаться на окрашивание?":
            bot.send_message(message.chat.id, "Да, конечно. Подскажите пожалуйста удобную дату и время.", reply_markup=key)
            if message.text is not None:
                bot.send_message(message.chat.id, "Для более точного планирования времени процедуры ответьте на несколько вопросов:", reply_markup=markup)
                bot.send_message(message.chat.id, "Длинна ваших волос?", reply_markup=markup)
                if message.text is not None:
                    bot.send_message(message.chat.id, "Тип окрашивания (в один тон, с осветлением, переходом, мелирование)?", reply_markup)
                    if message.text is not None:
                        bot.send_message(message.chat.id, "Спасибо за ваши ответы, с вам свяжется наш администратор.", reply_markup=markup)
        else:
            bot.send_message(message.chat.id, "Мы ничего не нашли по вашему вопросу, можете спросить у нашего администратора @DaryaPetkevich", reply_markup=markup)
                
            #ЗАКОНЧИТЬ ВЕСЬ СПИСОК ВОПРОСОВ


@bot.callback_query_handler(func=lambda call: True)
def model(call):
    print("- - -")
    print(call)
    print("- - -")
    print(" ")
    print(" ")
    print(" ")
    if call.message:
        if call.data == "Окрашивание":
            bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text="Укажите пожалуйста длинну ваших волос")
            if current_message is not None:
                bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text="Укажите исходный цвет")
                if current_message  is not None:
                    bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text="Окрашены ли волосы в настоящий момент?")
                    if current_message is not None:
                        bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text="Согласны ли вы на экспериментальное окрашивание, на усмотрение мастера?")
                        if current_message is not None:
                            bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text= "По возможности отправьте мне фото волос, или напишите Нет, для пропуска этого вопроса.")
                            if current_message is not None:
                                bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text= "Спасибо заявка принята.")

        if call.data == "Прическа":
            bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text= "Укажите пожалуйста длинну ваших волос.")
            if call.message is not None:
                bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text="Укажите пожалуйста оттенок волос (брюнетка, блогдинка, шатенка, рыжая)")
                if call.message is not None:
                    bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text="Спасибо, заявка принята.")


        if call.data == "Макияж":
            bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text= "Укажите пожалуйста Ваш возраст.")
            if call.message is not None:
                bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text= "Присутствует ли на лице перманентный макияж?")
                if call.message is not None:
                    bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text= "Отправьте, пожалуйста, фото анфас.")
                    if call.message == "#фотография":
                        bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text="Спасибо, заявка принята.")

        if call.data == "Мужские стрижки":
            key = types.InlineKeyboardMarkup()
            button_1 = types.InlineKeyboardButton(text = "Модельная 600 руб.", callback_data="Модельная")
            button_2 = types.InlineKeyboardButton(text = "Комплекс мужской 800 руб.", callback_data="Комплекс мужской")
            button_3 = types.InlineKeyboardButton(text = "Детская до 7 лет 400 руб.", callback_data="Детская до 7 лет")
            button_4 = types.InlineKeyboardButton(text = "Спортивная (под насадку) 400 руб.", callback_data="Спортивная (под насадку)")
            button_5 = types.InlineKeyboardButton(text = "Наголо 250 руб.", callback_data="Наголо")
            button_6 = types.InlineKeyboardButton(text = "Окантовка 350 руб.", callback_data="Окантовка")
            button_7 = types.InlineKeyboardButton(text = "Оформление усов 100 руб.", callback_data="Оформление усов")
            button_8 = types.InlineKeyboardButton(text = "Оформление бороды 300 руб.", callback_data="Оформление бороды")
            button_9 = types.InlineKeyboardButton(text = "Тонирование бороды 450 руб.", callback_data="Тонирование бороды")
            button_10 = types.InlineKeyboardButton(text = "Тонирование волос от 700 руб.", callback_data="Тонирование волос")
            key.add(button_1)
            key.add(button_2)
            key.add(button_3)
            key.add(button_4)
            key.add(button_5)
            key.add(button_6)
            key.add(button_7)
            key.add(button_8)
            key.add(button_9)
            key.add(button_10)
            bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text= "Выберите процедуру которую хотите заказать", reply_markup=key)
        elif call.data == "Женские стрижки":
            key = types.InlineKeyboardMarkup()
            button_1 = types.InlineKeyboardButton(text = "Короткая 750 руб.", callback_data="Короткая")
            button_2 = types.InlineKeyboardButton(text = "Средняя длинна 1050 руб.", callback_data="Средняя длинна")
            button_3 = types.InlineKeyboardButton(text = "Комплекс женский 1350 руб.", callback_data="Комплекс женский")
            button_4 = types.InlineKeyboardButton(text = "Мытье головы 150 руб.", callback_data="Мытье головы")
            button_5 = types.InlineKeyboardButton(text = "Уходовая маска 150 руб.", callback_data="Уходовая маска")
            button_6 = types.InlineKeyboardButton(text = "Стрижка кончиков 400 руб.", callback_data="Стрижка кончиков")
            button_7 = types.InlineKeyboardButton(text = "Оформление чёлки 250 руб.", callback_data="Оформление чёлки")
            button_8 = types.InlineKeyboardButton(text = "Укладка феном 500-700 руб.", callback_data="Укладка феном")
            button_9 = types.InlineKeyboardButton(text = "Плетение кос от 500 руб.", callback_data="Плетение кос")
            button_10 = types.InlineKeyboardButton(text = "Вечерняя причёска 2000-2500 руб.", callback_data="Вечерняя причёска")
            button_11 = types.InlineKeyboardButton(text = "Кератиновое выпрям. от 2500 руб.", callback_data="Кератиновое выпрям.")
            button_12= types.InlineKeyboardButton(text = "Окрашивание волос от 3000 руб.", callback_data="Окрашивание волос")
            button_13 = types.InlineKeyboardButton(text = "Снятие цвета от 1500 руб.", callback_data="Снятие цвета")
            key.add(button_1)
            key.add(button_2)
            key.add(button_3)
            key.add(button_4)
            key.add(button_5)
            key.add(button_6)
            key.add(button_7)
            key.add(button_8)
            key.add(button_9)
            key.add(button_10)
            key.add(button_11)
            key.add(button_12)
            key.add(button_13)
            bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text= "Выберите процедуру которую хотите заказать", reply_markup=key)
        elif call.data == "Маникюр":
            key = types.InlineKeyboardMarkup()
            button_1 = types.InlineKeyboardButton(text = "Класический 500 руб.", callback_data="Класический")
            button_2 = types.InlineKeyboardButton(text = "Аппаратный 500 руб.", callback_data="Аппаратный")
            button_3 = types.InlineKeyboardButton(text = "Комбинированный 500 руб.", callback_data="Комбинированный")
            button_4 = types.InlineKeyboardButton(text = "Мужской 650 руб.", callback_data="Мужской")
            button_5 = types.InlineKeyboardButton(text = "Покрытие шеллак 1000 руб.", callback_data="Покрытие шеллак")
            button_6 = types.InlineKeyboardButton(text = "Укрепление пластины гелем 600 руб.", callback_data="Укрепление пластины гелем")
            button_7 = types.InlineKeyboardButton(text = "Укрепление акрилом 350 руб.", callback_data="Укрепление акрилом")
            button_8 = types.InlineKeyboardButton(text = "Европейский 450 руб.", callback_data="Европейский")
            button_9 = types.InlineKeyboardButton(text = "Японский 1200 руб.", callback_data="Японский")
            button_10 = types.InlineKeyboardButton(text = "Детский 400 руб.", callback_data="Детский")
            button_11 = types.InlineKeyboardButton(text = "Снятие гель-лака 250 руб.", callback_data="Снятие гель-лака")
            button_12= types.InlineKeyboardButton(text = "Дизайн 50-100 руб. за 1 ноготь", callback_data="Дизайн")
            button_13 = types.InlineKeyboardButton(text = "Наращивание гелем 2500 руб.", callback_data="Наращивание гелем")
            key.add(button_1)
            key.add(button_2)
            key.add(button_3)
            key.add(button_4)
            key.add(button_5)
            key.add(button_6)
            key.add(button_7)
            key.add(button_8)
            key.add(button_9)
            key.add(button_10)
            key.add(button_11)
            key.add(button_12)
            key.add(button_13)
            bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text= "Выберите процедуру которую хотите заказать", reply_markup=key)
        elif call.data == "Педикюр":
            key = types.InlineKeyboardMarkup()
            button_1 = types.InlineKeyboardButton(text = "Класический женский 1300 руб.", callback_data="Класический женский")
            button_2 = types.InlineKeyboardButton(text = "Класический мужской 1600 руб.", callback_data="Класический мужской")
            button_3 = types.InlineKeyboardButton(text = "Кислотный женский 1600 руб.", callback_data="Кислотный женский")
            button_4 = types.InlineKeyboardButton(text = "Кислотный мужской 1800 руб.", callback_data="Кислотный мужской")
            button_5 = types.InlineKeyboardButton(text = "Обработка пальцев ног 800 руб.", callback_data="Обработка пальцев ног")
            button_6 = types.InlineKeyboardButton(text = "Паравинотерапия ног, рук 400 руб.", callback_data="Паравинотерапия ног, рук")
            key.add(button_1)
            key.add(button_2)
            key.add(button_3)
            key.add(button_4)
            key.add(button_5)
            key.add(button_6)
            bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text= "Выберите процедуру которую хотите заказать", reply_markup=key)
        elif call.data == "Косметология":
            key = types.InlineKeyboardMarkup()
            button_1 = types.InlineKeyboardButton(text = "Механическая чистка лица 2000 руб.", callback_data="Механическая чистка лица")
            button_2 = types.InlineKeyboardButton(text = "Ультразвук. чиска лица 1700 руб.", callback_data="Ультразвук. чиска лица")
            button_3 = types.InlineKeyboardButton(text = "Комбин.чистка лица 2500 руб.", callback_data="Комбин.чистка лица")
            button_4 = types.InlineKeyboardButton(text = "Пилинг по типу кожи 2000-3500 руб.", callback_data="Пилинг по типу кожи")
            button_5 = types.InlineKeyboardButton(text = "Уход по типу кожи 2000-3500 руб.", callback_data="Уход по типу кожи")
            button_6 = types.InlineKeyboardButton(text = "Буккальний массаж лица 1900 руб.", callback_data="Буккальний массаж лица")
            button_7 = types.InlineKeyboardButton(text = "Микроволновая терапия лица 900 руб.", callback_data="Микроволновая терапия лица")
            button_8 = types.InlineKeyboardButton(text = "Терапия лицо+шея+декольте 1200 руб.", callback_data="Терапия лицо+шея+декольте")
            button_9 = types.InlineKeyboardButton(text = "Удаление татуажа 1500 руб.", callback_data="Удаление татуажа")
            button_10 = types.InlineKeyboardButton(text = "Удаление татуировок 1500 руб.", callback_data="Удаление татуировок")
            button_11 = types.InlineKeyboardButton(text = "Крабовый пилинг 3500 руб.", callback_data="Крабовый пилинг")
            button_12 = types.InlineKeyboardButton(text = "Пирсинг от 1000 руб.", callback_data="Пирсинг")
            key.add(button_1)
            key.add(button_2)
            key.add(button_3)
            key.add(button_4)
            key.add(button_5)
            key.add(button_6)
            key.add(button_7)
            key.add(button_8)
            key.add(button_9)
            key.add(button_10)
            key.add(button_11)
            key.add(button_12)
            bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text= "Выберите процедуру которую хотите заказать", reply_markup=key)
        elif call.data == "SHR-эпиляция женский зал":
            key = types.InlineKeyboardMarkup()
            button_1 = types.InlineKeyboardButton(text = "Классическое бикини 3100 руб.", callback_data="Классическое бикини")
            button_2 = types.InlineKeyboardButton(text = "Глубокое бикини 5000 руб.", callback_data="Глубокое бикини")
            button_3 = types.InlineKeyboardButton(text = "Живот 1500-3200 руб.", callback_data="Живот")
            button_4 = types.InlineKeyboardButton(text = "Ноги (бедра) 8300 руб.", callback_data="Ноги (бедра)")
            button_5 = types.InlineKeyboardButton(text = "Ноги (голень) 4700 руб.", callback_data="Ноги (голень)")
            button_6 = types.InlineKeyboardButton(text = "Ноги полностью 9800 руб.", callback_data="Ноги полностью")
            button_7 = types.InlineKeyboardButton(text = "Пальцы ног 900 руб.", callback_data="Пальцы ног")
            button_8 = types.InlineKeyboardButton(text = "Подмышечные впадины 2300 руб.", callback_data="Подмышечные впадины")
            button_9 = types.InlineKeyboardButton(text = "Руки до локтя 3700 руб.", callback_data="Руки до локтя")
            button_10 = types.InlineKeyboardButton(text = "Руки полностью 5100 руб.", callback_data="Руки полностью")
            button_11 = types.InlineKeyboardButton(text = "Верхняя губа 950 руб.", callback_data="Верхняя губа")
            button_12 = types.InlineKeyboardButton(text = "Шея 1200-2800 руб.", callback_data="Шея")
            button_13 = types.InlineKeyboardButton(text = "Щеки 1800 руб.", callback_data="Щеки")
            button_14 = types.InlineKeyboardButton(text = "Подбородок 850 руб.", callback_data="Подбородок")
            button_15 = types.InlineKeyboardButton(text = "Бакенбарды 1200 руб.", callback_data="Бакенбарды")
            key.add(button_1)
            key.add(button_2)
            key.add(button_3)
            key.add(button_4)
            key.add(button_5)
            key.add(button_6)
            key.add(button_7)
            key.add(button_8)
            key.add(button_9)
            key.add(button_10)
            key.add(button_11)
            key.add(button_12)
            key.add(button_13)
            key.add(button_14)
            key.add(button_15)
            bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text= "Выберите процедуру которую хотите заказать", reply_markup=key)
        elif call.data == "SHR-эпиляция мужской зал":
            key = types.InlineKeyboardMarkup()
            button_1 = types.InlineKeyboardButton(text = "Бакенбарды 1200 руб.", callback_data="Бакенбарды")
            button_2 = types.InlineKeyboardButton(text = "Щеки 2300 руб.", callback_data="Щеки")
            button_3 = types.InlineKeyboardButton(text = "Грудь 4700 руб.", callback_data="Грудь")
            button_4 = types.InlineKeyboardButton(text = "Живот полностью 5000-6600 руб.", callback_data="Живот полностью")
            button_5 = types.InlineKeyboardButton(text = "Живот нижняя часть 4800 руб.", callback_data="Живот нижняя часть")
            button_6 = types.InlineKeyboardButton(text = "Ноги до колена 6600 руб.", callback_data="Ноги до колена")
            button_7 = types.InlineKeyboardButton(text = "Ноги полностью 11200 руб.", callback_data="Ноги полностью")
            button_8 = types.InlineKeyboardButton(text = "Пальцы ног 1800 руб.", callback_data="Пальцы ног")
            button_9 = types.InlineKeyboardButton(text = "Подмышечные впадины 2700 руб.", callback_data="Подмышечные впадины")
            button_10 = types.InlineKeyboardButton(text = "Руки до локтя 5000 руб.", callback_data="Руки до локтя")
            button_11 = types.InlineKeyboardButton(text = "Рики полностью 7100 руб.", callback_data="Рики полностью")
            button_12 = types.InlineKeyboardButton(text = "Спина 9500 руб.", callback_data="Спина")
            button_13 = types.InlineKeyboardButton(text = "Шея (задняя часть) 2300 руб.", callback_data="Шея (задняя часть)")
            button_14 = types.InlineKeyboardButton(text = "Шея (передняя часть) 2300 руб.", callback_data="Шея (передняя часть)")
            button_15 = types.InlineKeyboardButton(text = "Лицо полностью 4800 руб.", callback_data="Лицо полностью")
            key.add(button_1)
            key.add(button_2)
            key.add(button_3)
            key.add(button_4)
            key.add(button_5)
            key.add(button_6)
            key.add(button_7)
            key.add(button_8)
            key.add(button_9)
            key.add(button_10)
            key.add(button_11)
            key.add(button_12)
            key.add(button_13)
            key.add(button_14)
            key.add(button_15)
            bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text= "Выберите процедуру которую хотите заказать", reply_markup=key)
        elif call.data == "Солярий":
            key = types.InlineKeyboardMarkup()
            button_1 = types.InlineKeyboardButton(text = "Солярий 1 минута 20 руб.", callback_data="Солярий 1 минута")
            button_2 = types.InlineKeyboardButton(text = "Абонемент на 100 минут 1700 руб.", callback_data="Абонемент на 100 минут")
            button_3 = types.InlineKeyboardButton(text = "Абонемент на 50 минут 900 руб.", callback_data="Абонемент на 50 минут")
            key.add(button_1)
            key.add(button_2)
            key.add(button_3)
            bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text= "Выберите процедуру которую хотите заказать", reply_markup=key)
        elif call.data == "Шугаринг женский зал":
            key = types.InlineKeyboardMarkup()
            button_1 = types.InlineKeyboardButton(text = "Класический бикини 950 руб.", callback_data="Класический бикини")
            button_2 = types.InlineKeyboardButton(text = "Глубокое бикини 1500 руб.", callback_data="Глубокое бикини")
            button_3 = types.InlineKeyboardButton(text = "Голень 750 руб.", callback_data="Голень")
            button_4 = types.InlineKeyboardButton(text = "Ноги полностью 1200 руб.", callback_data="Ноги полностью")
            button_5 = types.InlineKeyboardButton(text = "Руки полностью 650 руб.", callback_data="Руки полностью")
            button_6 = types.InlineKeyboardButton(text = "Лицо 300 руб.", callback_data="Лицо")
            button_7 = types.InlineKeyboardButton(text = "Подмышки 450 руб.", callback_data="Подмышки")
            key.add(button_1)
            key.add(button_2)
            key.add(button_3)
            key.add(button_4)
            key.add(button_5)
            key.add(button_6)
            key.add(button_7)
            bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text= "Выберите процедуру которую хотите заказать", reply_markup=key)
        elif call.data == "Шугаринг мужской зал":
            key = types.InlineKeyboardMarkup()
            button_1 = types.InlineKeyboardButton(text = "Грудь 1500 руб.", callback_data="Грудь")
            button_2 = types.InlineKeyboardButton(text = "Спина 1500 руб.", callback_data="Спина")
            button_3 = types.InlineKeyboardButton(text = "Живот 1000 руб.", callback_data="Живот")
            button_4 = types.InlineKeyboardButton(text = "Ноги полностью 2500 руб.", callback_data="Ноги полностью")
            button_5 = types.InlineKeyboardButton(text = "Ноги голень 1400 руб.", callback_data="Ноги голень")
            button_6 = types.InlineKeyboardButton(text = "Ягодицы 750 руб.", callback_data="Ягодицы")
            button_7 = types.InlineKeyboardButton(text = "Руки полностью 1150 руб.", callback_data="Руки полностью")
            button_8 = types.InlineKeyboardButton(text = "Руки до локтя 750 руб.", callback_data="Руки до локтя")
            button_9 = types.InlineKeyboardButton(text = "Лицо 500 руб.", callback_data="Лицо")
            button_10 = types.InlineKeyboardButton(text = "Подмышки 650 руб.", callback_data="Подмышки")
            button_11 = types.InlineKeyboardButton(text = "Класическое бикини 2500 руб.", callback_data="Класическое бикини")
            button_12 = types.InlineKeyboardButton(text = "Глубокое бикини 4000 руб.", callback_data="Глубокое бикини")
            key.add(button_1)
            key.add(button_2)
            key.add(button_3)
            key.add(button_4)
            key.add(button_5)
            key.add(button_6)
            key.add(button_7)
            key.add(button_8)
            key.add(button_9)
            key.add(button_10)
            key.add(button_11)
            key.add(button_12)
            bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text= "Выберите процедуру которую хотите заказать", reply_markup=key)
        elif call.data == "БРОВИ И РЕСНИЦЫ":
            key = types.InlineKeyboardMarkup()
            button_1 = types.InlineKeyboardButton(text = "Наращивание ресниц 1800 руб.", callback_data="Наращивание ресниц")
            button_2 = types.InlineKeyboardButton(text = "Наращивание ресниц 2д 2000 руб.", callback_data="Наращивание ресниц 2д")
            button_3 = types.InlineKeyboardButton(text = "Наращивание ресниц 3д 2300 руб.", callback_data="Наращивание ресниц 3д")
            button_4 = types.InlineKeyboardButton(text = "Снятие нарощеных ресниц 400 руб.", callback_data="Снятие нарощеных ресниц")
            button_5 = types.InlineKeyboardButton(text = "Ламинирование ресниц 1900 руб.", callback_data="Ламинирование ресниц")
            button_6 = types.InlineKeyboardButton(text = "Коррекция бровей 300 руб.", callback_data="Коррекция бровей")
            button_7 = types.InlineKeyboardButton(text = "Окрашивание бровей краской 300 руб.", callback_data="Окрашивание бровей краской")
            button_8 = types.InlineKeyboardButton(text = "Окрашивание бровей хной 500 руб.", callback_data="Окрашивание бровей хной")
            button_9 = types.InlineKeyboardButton(text = "Ламинирование бровей 1100 руб.", callback_data="Ламинирование бровей")
            key.add(button_1)
            key.add(button_2)
            key.add(button_3)
            key.add(button_4)
            key.add(button_5)
            key.add(button_6)
            key.add(button_7)
            key.add(button_8)
            key.add(button_9)
            bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text= "Выберите процедуру которую хотите заказать", reply_markup=key)
        elif call.data == "Татуаж":
            key = types.InlineKeyboardMarkup()
            button_1 = types.InlineKeyboardButton(text = "Татуаж бровей 5500 руб.", callback_data="Татуаж бровей")
            button_2 = types.InlineKeyboardButton(text = "Татуаж губ 6500 руб.", callback_data="Татуаж губ")
            button_3 = types.InlineKeyboardButton(text = "Татуаж глаз 4500 руб.", callback_data="Татуаж глаз")
            button_4 = types.InlineKeyboardButton(text = "Коррекция - 59% от стоимости", callback_data="Коррекция")
            button_5 = types.InlineKeyboardButton(text = "Худ. татуировка от 3500 руб.", callback_data="Худ. татуировка")
            key.add(button_1)
            key.add(button_2)
            key.add(button_3)
            key.add(button_4)
            key.add(button_5)
            bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text= "Выберите процедуру которую хотите заказать", reply_markup=key)
        elif call.data == "Отбеливание зубов Smile ROOM":
            key = types.InlineKeyboardMarkup()
            button_1 = types.InlineKeyboardButton(text = "Экспресс 2550 руб.", callback_data="Экспресс")
            button_2 = types.InlineKeyboardButton(text = "Двойное 3600 руб.", callback_data="Двойное")
            button_3 = types.InlineKeyboardButton(text = "Максимальное 3900 руб.", callback_data="Максимальное")
            key.add(button_1)
            key.add(button_2)
            key.add(button_3)
            bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text= "Выберите процедуру которую хотите заказать", reply_markup=key)
        elif call.data == "Макияж":
            key = types.InlineKeyboardMarkup()
            button_1 = types.InlineKeyboardButton(text = "Макияж Дневной 1700 руб.", callback_data="Макияж Дневной")
            button_2 = types.InlineKeyboardButton(text = "Вечерний 2000 руб.", callback_data="Вечерний")
            button_3 = types.InlineKeyboardButton(text = "Свадебный 2000-2500 руб.", callback_data="Свадебный")
            key.add(button_1)
            key.add(button_2)
            key.add(button_3)
            bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text= "Выберите процедуру которую хотите заказать", reply_markup=key)


if __name__ == '__main__':
    bot.polling(none_stop=True)
